### ISSUE TITLE
Add installation instructions to README.md

### ISSUE THREAD

**Issue by gregtucker** [csdms/pymt#98]
The pymt README should instruct potential users how to install the software, and what docs or examples or notebooks to look at to get started.

**Comment by gregtucker** [comment]
A user who is somewhat familiar with conda might guess, as I did, that you can create a conda environment with a complete pymt-compatible installation, and then import and run pymt, by doing the following:

1) git clone https://github.com/csdms/pymt.git
2) conda env create -n pymt -f environment.yml
3) conda activate pymt
4) ipython
5) in ipython: import pymt

However, when I do all this:

(pymt) Greg-Tuckers-MacBook-Pro:~ gtucker$ ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pymt                                                             
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a062ed831948> in <module>
----> 1 import pymt

ModuleNotFoundError: No module named 'pymt'

In [2]: exit                                                                    
(pymt) Greg-Tuckers-MacBook-Pro:~ gtucker$ conda install pymt
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

**Comment by mcflugen** [comment]
@gregtucker Thanks for looking at this. The docs are somewhat in flux right now.

In the *README* there is a link to the *pymt* docs on [*readthedocs*](https://pymt.rtfd.io). This is where the installation instructions are located. Clearly, the link needs to be more obvious!

The environment file you found was recently added by @gantian127 so that we can run *pymt* on binder. It should, though, still work for creating a new, fresh, environment for *pymt* to run in. I believe the problem you are seeing is because your *ipython* is outside your newly-created environment and so doesn't see the packages you just installed. I suspect this is the case since *ipython* is not listed in the *environment.yml* file you used and, as such, shouldn't have been installed (i.e. you should get `ipython: command not found`). This is probably a PATH issue and/or you have multiple Pythons installed on your machine.

If you do the following, do you get paths to different locations for *python* and *ipython*?
```bash
$ conda activate pymt
$ which python
$ which ipython
```

**Comment by gregtucker** [comment]
Thanks @mcflugen! I didn't think to click on the "docs" badge. I do think it would be helpful to potential users to have some kind of prominent text in the readme indicating a link to installation instructions (and to the docs generally).

You're quite right about the conda environment, my bad. It works beautifully now that I've added ipython and jupyter to my pymt conda environment.

**Comment by mdpiper** [comment]
Links to installation instructions and the user documentation are now provided in the README.
